import { Book } from './book.model';

export const BOOKS: Book[] = [
  {
    id: 1,
    author: 'J.K. Rowling',
    title: 'Harry Potter és a bölcsek köve',
    year: 1997,
    cost: 5500,
    rating: 5,
  },
  {
    id: 2,
    author: 'J.R.R. Tolkien',
    title: 'A gyűrűk ura: A gyűrűszövetsége',
    year: 1954,
    cost: 14000,
    rating: 4.9,
  },
  {
    id: 3,
    author: 'George Orwell',
    title: '1984',
    year: 1949,
    cost: 3000,
    rating: 4.8,
  },
  {
    id: 4,
    author: 'Frank Herbert',
    title: 'Dűne',
    year: 1965,
    cost: 3800,
    rating: 4.7,
  },
  {
    id: 5,
    author: 'Harper Lee',
    title: 'Ne bántsátok a feketerigót!',
    year: 1960,
    cost: 3200,
    rating: 4.6,
  },
  {
    id: 6,
    author: 'Jane Austen',
    title: 'Büszkeség és balítélet',
    year: 1813,
    cost: 2800,
    rating: 4.5,
  },
  {
    id: 7,
    author: 'Mark Twain',
    title: 'Huckleberry Finn kalandjai',
    year: 1884,
    cost: 3100,
    rating: 4.4,
  },
  {
    id: 8,
    author: 'F. Scott Fitzgerald',
    title: 'A nagy Gatsby',
    year: 1925,
    cost: 3400,
    rating: 4.3,
  },
  {
    id: 9,
    author: 'Leo Tolstoy',
    title: 'Háború és béke',
    year: 1869,
    cost: 7500,
    rating: 4.8,
  },
  {
    id: 10,
    author: 'Herman Melville',
    title: 'Moby Dick',
    year: 1851,
    cost: 3700,
    rating: 4.2,
  },
  {
    id: 11,
    author: 'Ernest Hemingway',
    title: 'Az öreg halász és a tenger',
    year: 1952,
    cost: 1400,
    rating: 4.1,
  },
  {
    id: 12,
    author: 'John Steinbeck',
    title: 'Harag',
    year: 1939,
    cost: 3300,
    rating: 4.5,
  },
  {
    id: 13,
    author: 'Margaret Atwood',
    title: 'A szolgálólány meséje',
    year: 1985,
    cost: 3600,
    rating: 4.6,
  },
  {
    id: 14,
    author: 'Aldous Huxley',
    title: 'Szép új világ',
    year: 1932,
    cost: 3400,
    rating: 4.5,
  },
  {
    id: 15,
    author: 'Charles Dickens',
    title: 'Két város regénye',
    year: 1859,
    cost: 3500,
    rating: 4.3,
  },
  {
    id: 16,
    author: 'Ray Bradbury',
    title: 'Fahrenheit 451',
    year: 1953,
    cost: 3200,
    rating: 4.4,
  },
  {
    id: 17,
    author: 'Gabriel García Márquez',
    title: 'Száz év magány',
    year: 1967,
    cost: 4000,
    rating: 5,
  },
  {
    id: 18,
    author: 'William Golding',
    title: 'A legyek ura',
    year: 1954,
    cost: 5100,
    rating: 4.0,
  },
  {
    id: 19,
    author: 'Joseph Conrad',
    title: 'A sötétség szíve',
    year: 1899,
    cost: 2800,
    rating: 4.1,
  },
  {
    id: 20,
    author: 'E. M. Forster',
    title: 'Út Indiába',
    year: 1924,
    cost: 1300,
    rating: 4.2,
  },
  {
    id: 21,
    author: 'Oscar Wilde',
    title: 'A Dorian Gray portréja',
    year: 1890,
    cost: 3000,
    rating: 4.4,
},
{
    id: 22,
    author: 'Louisa May Alcott',
    title: 'Kisasszonyok',
    year: 1868,
    cost: 2900,
    rating: 4.5,
},
{
    id: 23,
    author: 'Emily Brontë',
    title: 'Üvöltő szelek',
    year: 1847,
    cost: 3100,
    rating: 4.3,
},
{
    id: 24,
    author: 'Charlotte Brontë',
    title: 'Jane Eyre',
    year: 1847,
    cost: 3200,
    rating: 4.5,
},
{
    id: 25,
    author: 'Bram Stoker',
    title: 'Drakula',
    year: 1897,
    cost: 3300,
    rating: 4.4,
},
{
    id: 26,
    author: 'Mary Shelley',
    title: 'Frankenstein',
    year: 1818,
    cost: 3400,
    rating: 4.2,
},
{
    id: 27,
    author: 'Victor Hugo',
    title: 'A párizsi Notre Dame',
    year: 1831,
    cost: 3500,
    rating: 4.4,
},
{
    id: 28,
    author: 'H.G. Wells',
    title: 'A világok háborúja',
    year: 1898,
    cost: 3600,
    rating: 4.3,
},
{
    id: 29,
    author: 'Lewis Carroll',
    title: 'Alice Csodaországban',
    year: 1865,
    cost: 3400,
    rating: 4.5,
},
{
    id: 30,
    author: 'Mark Twain',
    title: 'Tom Sawyer kalandjai',
    year: 1876,
    cost: 3500,
    rating: 4.6,
},
{
    id: 31,
    author: 'Robert Louis Stevenson',
    title: 'A kincses sziget',
    year: 1883,
    cost: 3200,
    rating: 4.7,
},
{
    id: 32,
    author: 'Herman Hesse',
    title: 'Sziddhártha',
    year: 1922,
    cost: 3700,
    rating: 4.6,
},
{
    id: 33,
    author: 'Antoine de Saint-Exupéry',
    title: 'A kis herceg',
    year: 1943,
    cost: 2800,
    rating: 5.0,
},
{
    id: 34,
    author: 'Miguel de Cervantes',
    title: 'Don Quijote',
    year: 1605,
    cost: 3800,
    rating: 4.6,
},
{
    id: 35,
    author: 'John Milton',
    title: 'Paradicsom elvesztése',
    year: 1667,
    cost: 4000,
    rating: 4.4,
},
{
    id: 36,
    author: 'James Joyce',
    title: 'Ulysses',
    year: 1922,
    cost: 3900,
    rating: 4.3,
},
{
    id: 37,
    author: 'Fjodor Dostojevszkij',
    title: 'Bűn és bűnhődés',
    year: 1866,
    cost: 4200,
    rating: 4.8,
},
{
    id: 38,
    author: 'Nathaniel Hawthorne',
    title: 'A skarlát betű',
    year: 1850,
    cost: 3100,
    rating: 4.2,
},
{
    id: 39,
    author: 'Thomas Hardy',
    title: 'Tess, a d’Urberville-iak',
    year: 1891,
    cost: 3300,
    rating: 4.1,
},
{
    id: 40,
    author: 'Homérosz',
    title: 'Iliász',
    year: -750,
    cost: 3700,
    rating: 4.5,
}
];
